# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-Dining
version:      1.01
version_from: lib/Crypt/Dining.pm
installdirs:  site
requires:
    Crypt::Random:                 0
    Net::Address::IPv4::Local:     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.20
